apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sample-azure-k8n-deployment
  labels:
    app: sample-azure-k8n
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-azure-k8n
  template:
    metadata:
      labels:
        app: sample-azure-k8n
    spec:
      containers:
      - name: sample-azure-k8n
        image: azurus.azurecr.io/sample-azure-k8n:10
        volumeMounts:
        - name: cosmos-credentials
          mountPath: /etc/cosmos-credentials
          readOnly: true
      volumes:
      - name: cosmos-credentials
        secret:
          secretName: cosmos-credentials