kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: sample-azure-k8n
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: request-storage-service
spec:
  type: ExternalName
  externalName: azurus.documents.azure.com
